apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: klintondocker/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: klintondocker/client
      context: client
      sync:
        manual:
          - src: '**/*.js,*.jsx'
            dest: .
      docker:
        dockerfile: Dockerfile
